Module3 task2
htmlacademy-php/29559-readme-12 pull request #7
Opened 2020-05-25 20:39 UTC by dtumanenkov

2020-05-26 05:52 UTC, shershnevsergey requested changes
Еще необходимо сделать это:

> Дату в оригинальном формате без изменений показывайте внутри атрибута datetime этого тега.

И в целом поправить форматирование кода

2020-05-26 05:52 UTC, Shv-sergey70 commented on index.php
> +    $sec_in_day=86400;
Обычно до и после знака равно ставятся пробелы

2020-05-26 05:52 UTC, Shv-sergey70 commented on index.php
> +    if($ts_diff<=60){ //менее 60 сек
тут тоже пробелы перед знаком сравнения

2020-05-26 05:52 UTC, Shv-sergey70 commented on index.php
> +    elseif($ts_diff<=3600 && $ts_diff>60){ //менее 60 минут
Изучи стандарт psr-2, по критериям, мы должны следовать ему. Да и вообще это хорошая практика:
https://www.php-fig.org/psr/psr-2/

Там регламентирован синтаксис if/elseif/else

2020-05-26 05:52 UTC, Shv-sergey70 commented on index.php
> +    $sec_in_day=86400;
Все константные можно объявить я помощью define в файле, который будет подгружаться перед каждой страницей. Например можно сделать `init.php`. В дальнейшем, в нем же мы опишем подключение к БД

2020-05-26 05:52 UTC, Shv-sergey70 commented on index.php
> +require_once('helpers.php');
Это лучше делать в самом начале файла

2020-05-26 05:52 UTC, Shv-sergey70 commented on templates/main.php
> +                            <a class="post__author-link" href="#" title="<?= $post_date=generate_random_date($key) ?>"> <!-- генерируем случайную дату по индексу массива постов-->
`<?= $post_date=generate_random_date($key) ?>` - тут сразу и присваивание, и вывод информации. Так лучше не делать. Объявите эту переменную сразу после начала цикла. И уже тут используйте только `$post_date `

2020-05-26 05:53 UTC, Shv-sergey70 commented on helpers.php
> +    $dt = date('d.m.Y H:i', $ts);
Так как дата в теге datetime должна быть в оригинальном формате, думаю это действие Вам не нужно

2020-05-26 20:36 UTC, dtumanenkov commented on index.php
> +    elseif($ts_diff<=3600 && $ts_diff>60){ //менее 60 минут
Как резать длинные комментарии > 120 ?

2020-05-27 15:55 UTC, Shv-sergey70 commented on init.php
> +define("sec_in_hour",3600); // константы времени
SEC_IN_HOUR, обычно константы пишут капсом

2020-05-27 15:55 UTC, Shv-sergey70 commented on index.php
> +    } elseif ($ts_diff <= 86400 && $ts_diff > 3600) { //менее 24 часов но более 60 минут
Вы ввели константы, а здесь так и не использовали(

2020-05-27 15:56 UTC, Shv-sergey70 commented on index.php
> +    $ts_diff = $ts - $end_ts;
Можно сразу
`$ts_diff = time() - strtotime($post_time);`

2020-05-27 15:57 UTC, Shv-sergey70 commented on index.php
> +function time_delta($post_time){    //подсчет разницы времени между публикацией и текущей датой
Вот пример phpDoc для функции
```
/**
 * Подсчет разницы времени между публикацией и текущей датой
 * 
 * @param $post_time
 *
 * @author Name Surname email@email.com
 *
 * @return string
 */
function time_delta($post_time) {
```

2020-05-29 16:23 UTC, Shv-sergey70 commented on index.php
> + * @author
Тут Ваша фамилия и имя + почта

2020-05-29 16:23 UTC, Shv-sergey70 commented on index.php
> +    if ($ts_diff <= 60) { /**менее 60 сек */
Для 60 секунд также не помешает константа

2020-05-29 16:23 UTC, merged